logging:
  name: "app_logger"
can:
  channel: "virtual"
  interface: "virtual"
  bitrate: 250000
serial:
  port: ""
  baudrate: 115200
  timeout: 0.1
video:
  rtsp_url: "src/example.mp4"
  sessions_db: "SessionsDB.json"
  dvr:
    url: "mock://dvr"
    user: "mock"
    password: "mock"
    dir: "mock_sessions"
# Para probar las cosas de diagn√≥stico
vision:
  mode: "real"          # "mock" o "real"
  base_url: "http://127.0.0.1:8000"
  ws_base_url: "ws://127.0.0.1:8000"
  timeout_seconds: 10

  model_id: "ONLY_DB03_V8"  # NUEVO: modelo fijo para operadores
